# This is a basic workflow to help you get started with Actions

name: WDIO-CI
on:
  push:
    branches: [ master, release]
  pull_request:
    branches: [ master, release]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add othe actions to build,
          echo test, and deploy project.